services:
  remote-gui:
    image: gui
    container_name: remote-gui
    restart: always
    stdin_open: true
    tty: true
    environment:
      VITE_API_URL: http://127.0.0.1:8080
    ports:
      - "3000:3000"
      - "31800:31800"
      - "8080:8080"
    volumes:
      - image-vol:/app/CLI/local-cli-backend/static/
      - usr-mgm-vol:/app/CLI/local-cli/backend/usr-mgm/
      - report-configs:/app/CLI/local-cli-backend/plugins/reportgenerator/templates
#  ollama-node:
#    container_name: ollama
#    image: ollama/ollama:latest
#    ports:
#      - "11435:11434"
#    volumes:
#      - ollama-data:/root/.ollama

volumes:
  image-vol:
  usr-mgm-vol:
  report-configs:
#  ollama-data:


